simple_mooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('entrar/', LoginView.as_view(), name='login'),
    path('sair/', LogoutView.as_view() , name='logout'),
    path('cadastrese/', views.register, name='register'),
    path('nova-senha/', views.password_reset, name='password_reset'),
    path('confirmar-nova-senha/<key>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit_password'),

]

simple_mooc/courses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:pk>/', views.details, name='details'),
    path('<slug:slug>/', views.details, name='details'),
    path('<slug:slug>/inscricao/', views.enrollment, name='enrollment'),
    path('<slug:slug>/cancelar-inscricao/', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/anuncios/', views.announcements, name='announcements'),
    path('<slug:slug>/anuncios/<int:pk>/', views.show_announcements, name='show_announcements'),
    path('<slug:slug>/aulas/', views.lessons, name='lessons'),
    path('<slug:slug>/aulas/<int:pk>/', views.lesson, name='lesson'),
    path('<slug:slug>/materiais/<int:pk>/', views.material, name='material'),

]


simple_mooc/urls.py
from django.contrib import admin
from django.urls import include, path

#importacao para poder usar imagens anexadas enao em pastas fixas
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('simple_mooc.polls.urls', 'polls'), namespace='polls' )),
    path('conta/', include(('simple_mooc.accounts.urls', 'accounts'), namespace='accounts' )),
    path('cursos/', include(('simple_mooc.courses.urls', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_mooc/accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core import validators
import re
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome de Usuario', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
        'Nome de usuario so pode conter letras, digitos ou @/./+/-/_', 'invalid' )]
    
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=30, blank=True)
    is_active = models.BooleanField('Esta ativo?', blank=True, default=True)
    is_staff = models.BooleanField('Esta da equipe?', blank=True, default=True)
    date_joined = models.DateTimeField(
        'Data de Entrada', auto_now_add=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

class PasswordReset(models.Model):
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuario',on_delete=models.CASCADE,
        related_name='resets'
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas senhas'
        ordering = ['-created_at']

simple_mooc/accounts/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import get_user_model

from simple_mooc.polls.mail import send_mail_template
from simple_mooc.polls.utils import generate_hash_key

from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail')
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuario encontrado com este e-mail'
        )
    
    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset =PasswordReset(user=user, key=key)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Crias nova senha'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])

class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'Senhas diferentes',
                code='password_mismatch'
            )
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    
    class Meta:
        model = User
        fields = ['username', 'email']

class EditAccountForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['username', 'email', 'name']

simple_mooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

from django.contrib.auth.forms import (
    UserCreationForm, PasswordChangeForm, SetPasswordForm
)
from django.conf import settings
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required

from simple_mooc.polls.utils import generate_hash_key
from simple_mooc.courses.models import Enrollment

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset


User = get_user_model()


@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)

def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=request.POST['username'], password = request.POST['password1']  
            )
            login(request,user)
            return redirect('polls:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)

def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

@login_required
def edit_password(request):
    template_name ='accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

simple_mooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
{% load_my_courses user as enrollments %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'accounts:dashboard'%}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">   
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Bem Vindo, {{ user }}
                </li>
                {% block menu_options %}
                <li class ="pure-menu-heading">Meus Cursos</li>
                {% for enrollment in enrollments %}
                <li>
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}">
                    <i class="fa fa-book"></i>
                        {{ enrollment.course }}
                    </a>
                </li>
                {% empty %}
                <li>Nenhum Curso Encontrado</li>
                {% endfor %}

                <li class="pure-menu-heading">Conta</li>
                <li>
                    <a href="{% url 'accounts:edit' %}">
                        <i class="fa fa-cog"></i>
                        Editar informações
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:edit_password' %}">
                        <i class="fa fa-lock"></i>
                        Editar Senha
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block breadcrumb_content %}
            <h2>Meus Cursos</h2>
            {% for enrollment in enrollments%}
            <div class="well">
                <h3>{{ enrollment.course }}
                    ({{ enrollment.course.start_date|date:"d/m/Y"|default:"Sem Data" }})
                </h3>
                {{ enrollment.course.description|linebreaks}}
                <div class="pure-controls">
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Acessar</a>
                    <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="pure-button button-error">Cancelar</a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1">
                <p>Nunhum Curso Inscrito</p>
            </aside>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simple_mooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit'%}">Editar Conta</a></li>
{% endblock %}

{% block breadcrumb_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Os dados foram alterados com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_erros}}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.erros }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">
            Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}
 

simple_mooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit'%}">Editar Senha</a></li>
{% endblock %}

{% block breadcrumb_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Senha alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_erros}}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.erros }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">
            Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simple_mooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Um e-mail foi enviado</p>
        {% else %}
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simple_mooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criado com Sucesso</p>
        {% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simple_mooc/accounts/templates/accounts/password_reset_mail.html
<p>Para criar nova senha acesse o link: <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key%}"
    title="Link para criar nova senha">Criar Nova Senha</a></p>

simple_mooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}