simple_mooc/courses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:pk>/', views.details, name='details'),
    path('<slug:slug>/', views.details, name='details'),
    path('<slug:slug>/inscricao/', views.enrollment, name='enrollment'),
    path('<slug:slug>/cancelar-inscricao/', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/anuncios/', views.announcements, name='announcements'),
    path('<slug:slug>/anuncios/<int:pk>/', views.show_announcements, name='show_announcements'),
    path('<slug:slug>/aulas/', views.lessons, name='lessons'),
    path('<slug:slug>/aulas/<int:pk>/', views.lesson, name='lesson'),
    path('<slug:slug>/materiais/<int:pk>/', views.material, name='material'),

]


simple_mooc/urls.py
from django.contrib import admin
from django.urls import include, path

#importacao para poder usar imagens anexadas enao em pastas fixas
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('simple_mooc.polls.urls', 'polls'), namespace='polls' )),
    path('conta/', include(('simple_mooc.accounts.urls', 'accounts'), namespace='accounts' )),
    path('cursos/', include(('simple_mooc.courses.urls', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_mooc/courses/models.py
from django.db import models
from django.urls import reverse #para funcionar permalink
from django.conf import settings
from django.utils import timezone

from simple_mooc.polls.mail import send_mail_template
# Create your models here.
class CourseManager(models.Manager):
    
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(description__icontains=query)    
        )


class Course(models.Model):
    
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição', blank=True)
    about = models.TextField('Sobre o Curso', blank=True)
    start_date = models.DateField(
        'Data de inicio', null=True, blank=True 
    )
    image = models.ImageField(
        upload_to='static', verbose_name='Imagem',
        null=True, blank=True
    )
    
    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CourseManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return (self.slug)

    def release_lessons(self):
        today = timezone.now().date()
        return self.lessons.filter(release_date__gte=today)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']


class Lesson(models.Model):
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descricao', blank=True)
    number = models.IntegerField('Ordem', blank=True, default=0)
    release_date = models.DateField('Data de Liberação', blank=True, null=True)

    course = models.ForeignKey(Course, verbose_name='Curso', related_name='lessons', on_delete=models.CASCADE)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.name

    def is_available(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date >= today
        return False

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['number']


class Material(models.Model):

    name = models.CharField('Nome', max_length=100)
    embedded = models.TextField('Video embedded', blank=True)
    file = models.FileField(upload_to='lessons/materials', blank=True, null=True)

    lesson = models.ForeignKey(Lesson, verbose_name='Aula', related_name='materials', on_delete=models.CASCADE)

    def is_embedded(self):
        return bool(self.embedded)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiais'


class Enrollment(models.Model):

    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Cancelado')
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuario',
        related_name='enrollments',
        on_delete=models.CASCADE
    )
    course = models.ForeignKey(
        Course, verbose_name='Usuario',
        related_name='enrollments',
        on_delete=models.CASCADE
    )
    status = models.IntegerField(
        'Situação', choices = STATUS_CHOICES, default=1, blank=True 
    )

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def active(self):
        self.status = 1
        self.save()

    def is_approved(self):
        return self.status == 1
        
    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrição'
        unique_together = (('user', 'course'))


class Announcement(models.Model):

    course = models.ForeignKey(
        Course, verbose_name = 'Curso', related_name='announcements', on_delete=models.CASCADE
    )
    title = models.CharField('Titulo', max_length=100)
    content = models.TextField('Conteudo')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Anuncios'
        verbose_name_plural = 'Anuncios'
        ordering = ['-created_at']


class Comment(models.Model):

    announcement = models.ForeignKey(
        Announcement, verbose_name='Anuncio', related_name='comments', on_delete=models.CASCADE
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='usuario', on_delete=models.CASCADE)
    comment = models.TextField('Comentario')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentarios'
        ordering = ['created_at']

def post_save_announcement(instance, created, **kwarrgs):
    if created:
        subject = instance.title
        context = {
            'announcement' : instance
        }
        template_name = 'courses/announcement_mail.html'
        enrollments = Enrollment.objects.filter(
            course=instance.course, status=1
        )
        for enrollment in enrollments:
            recipient_list = [enrollment.user.email]
            send_mail_template(subject, template_name, context, recipient_list)

models.signals.post_save.connect(
    post_save_announcement, sender=Announcement, dispatch_uid='post_save_annoucement'
    )



simple_mooc/courses/forms.py
from django import forms
#from django.core.mail import send_mail
from django.conf import settings

from simple_mooc.polls.mail import send_mail_template
from .models import Comment

class ContactCourse(forms.Form):

    #riquired = False / para dizer que campo nao é obrigatorio
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label = 'Mensagem/Duvida', widget=forms.Textarea,
    )

    def send_mail(self, course):
        subject = '[%s] Contato' % course
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'courses/contact_email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]
        )

    # Envio antigo, sem o uso de template
    # def send_mail(self, course):
    #     subject = '[%s] Contato' % course
    #     message = 'Nome: %(name)s;E-mail: %(email)s;%(message)s'
    #     context = {
    #         'name': self.cleaned_data['name'],
    #         'email': self.cleaned_data['email'],
    #         'message': self.cleaned_data['message'],
    #     }
    #     message = message % context
    #     send_mail(
    #         subject, message, settings.DEFAULT_FROM_EMAIL, 
    #         [settings.CONTACT_EMAIL]
    #     )

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']

simple_mooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
#importacao dos models de cursos
from .models import Course, Enrollment, Announcement, Lesson, Material
#importando formularios
from .forms import ContactCourse, CommentForm
from django.contrib.auth.decorators import login_required
#colocando app de mensagens do django 
from django.contrib import messages
from .decotators import enrollment_required

# Create your views here.

def index(request):
    courses = Course.objects.all()
    template_name = 'courses/index.html'
    context = {
        'courses':courses
    }

    return render(request, template_name, context)

# Para passar parametro como ID
#def details(request, pk):
#    course = get_object_or_404(Course, pk=pk)
#    context = {
#        'course':course
#    }
#    template_name = 'courses/details.html'
#    return render(request, template_name, context)

# Para passar parametro como Slug
def details(request, slug):
    course = get_object_or_404(Course, slug=slug)
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course)
            form = ContactCourse()
    else:
        form = ContactCourse()
    context['form'] = form
    context['course'] = course
    template_name = 'courses/details.html'
    return render(request, template_name, context)

@login_required
def enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, course=course
    )
    if created:
        enrollment.active()
        messages.success(request, 'Voce foi inscrito com sucesso')
    else:
        messages.info(request,'Voce ja esta inscrito no curso')
    return redirect('accounts:dashboard')

@login_required
def undo_enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(
            Enrollment, user=request.user, course=course
    )
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua Incrinção foi Cancelada')
        return redirect('accounts:dashboard')
    template = 'courses/undo_enrollment.html'
    context = {
        'enrollment': enrollment,
        'course': course
    }
    return render(request, template, context)

@login_required
@enrollment_required
def announcements(request, slug):
    course = request.course
    template = 'courses/announcements.html'
    context = {
        'course': course,
        'announcements': course.announcements.all()
    }
    return render(request, template, context )

@login_required
def show_announcements(request, slug, pk):
    course = get_object_or_404(Course, slug=slug)
    if not request.user.is_staff:
        enrollment = get_object_or_404(
            Enrollment, user=request.user, course=course
        )
        if not enrollment.is_approved():
            messages.erros(request, 'Inscricao Pendente')
            return redirect('accounts:dashboard')
    announcement = get_object_or_404(course.announcements.all(), pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save()
        form = CommentForm()
        messages.success(request, 'Seu comentario foi enviado')
    template = 'courses/show_announcements.html'
    context = {
        'course': course,
        'announcement': announcement,
        'form': form

    }
    return render(request, template, context )


@login_required
@enrollment_required
def lessons(request, slug):
    course = request.course
    template = 'courses/lessons.html'
    lessons = course.release_lessons()
    if request.user.is_staff:
        lessons = course.lessons.all()
    context = {
        'course': course,
        'lessons': lessons
    }
    return render(request, template, context)


@login_required
@enrollment_required
def lesson(request, slug, pk):
    course = request.course
    lesson = get_object_or_404(Lesson, pk=pk, course=course)
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta aula não esta disponivel')
        return redirect('courses:lessons', slug=course.slug)
    template = 'courses/lesson.html'
    context = {
        'course': course,
        'lesson': lesson
    }
    return render(request, template, context)


@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    material = get_object_or_404(Material, pk=pk, lesson__course=course)
    lesson = material.lesson
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esre material não esta disponivel')
        return redirect('courses:lesson', slug=course.slug, pk=lesson.pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template = 'courses/material.html'
    context = {
        'course': course,
        'lesson': lesson,
        'material': material
    }
    return render(request, template, context)

simple_mooc/courses/templates/courses/announcement_mail.html
{{ announcemment.content|linebreaks }}

simple_mooc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">Anuncios</a></li>
{% endblock %}

{% block breadcrumb_content %}
{% for announcement in announcements %}
<div class="well">
    <h2>
        <a href="{% url 'courses:show_announcements' course.slug announcement.pk %}">{{ announcement.title }}</a>
    </h2>
    {{ announcement.content|linebreaks }}
    <p>
        <a href="{% url 'courses:show_announcements' course.slug announcement.pk %}#comments">
        <i class="fa fa-comments-o"></i>
        {% with comments_count=announcement.comments.count %}
        {{ comments_count }}
        Comentário{{ comments_count|pluralize }}
        {% endwith %}
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>Nenhum Anuncio Encontrado</h2>
</div>
{% endfor %}
{% endblock %}


simple_mooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simple_mooc/courses/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
{% endblock %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="{% url 'courses:lessons' course.slug %}">
        <i class="fa fa-video-camera"></i>
        Aulas e Materias
    </a>
</li>
<li>
    <a href="">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="{% url 'courses:announcements' course.slug %}">
        <i class="fa fa-envelope"></i>
        Anuncios
    </a>
</li>
<li>
    <a href="">
        <i class="fa fa-comments"></i>
        Forum de Duvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

simple_mooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

simple_mooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
            {% if course.image %}    
            <img src="{{ course.image.url }}" alt="{{ course.name }}"/>
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}    
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty%}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum Curso disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

simple_mooc/courses/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block breadcrumb_content %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    {{ lesson.description|linebreaks}}
    <h4>Material da Aula</h4>
    <table class="pure-table full">
        <thead>
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    Ação
                </th>
            </tr>
        </thead>
        <tbody>
            {% for material in lesson.materials.all %}
            <tr class="{% cycle '' 'pure-table-odd' %}">
                <td> 
                    {{ material }} 
                </td>
                <td>
                    {% if material.is_embedded %}
                    <a href="{% url 'courses:material' course.slug material.pk %}">
                        <i class="fa fa-video-camera"></i>
                        Acessar
                    </a>
                    {% else %}
                    <a terged="_blank" href="{{ material.file.url }}">
                        <i class="fa fa-download"></i>
                        Baixar
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

simple_mooc/courses/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
{% endblock %}

{% block breadcrumb_content %}
{% for lesson in lessons %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }}
        <br />
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}" title="">
            <i class="fa fa-eye"></i>
            Acessar Aula
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>Nenhuma aula disponivel</h2>
</div>
{% endfor %}
{% endblock %}

simple_mooc/courses/templates/courses/material.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block breadcrumb_content %}
<div class="well">
    <h2><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}"></a></h2>
    {{ material.embedded|safe }}
    <p>
        <a href="{% url 'courses:material' course.slug lesson.pk %}">Voltar</a>
    </p>
</div>
{% endblock %}

simple_mooc/courses/templates/courses/show_announcements.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">Anuncios</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:show_announcements' course.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock %}

{% block breadcrumb_content %}
    <div class="well">
        <h2>{{ announcement.title }}</h2>
        {{ announcement.content|linebreaks }}
    </div>
    <div class="well">
        <h4 id="comments">Comentários
        <a class="fright" href="#add_comment">Comentar</a></h4>
        <hr />
        {% for comment in announcement.comments.all %}
        <p>
            <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
        <hr>
        {% empty %}
        <p>
            Nenhum comentário para este anúncio.
        </p>
        {% endfor %}
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

simple_mooc/courses/templates/courses/undo_enrollment.html
{% extends 'courses/course_dashboard.html' %}

{% block breadcrumb_content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>Voce deseja realmente cancelar a inscrição deste curso</h3>
    <div class="pure-controls">
        <button type="submit" class="pure-button button-error">
            Cancelar
        </button>
        <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button">
            Voltar
        </a>
    </div>
</form>
{% endblock %}